### ISSUE TITLE
Downloadable release assets

### ISSUE THREAD

**Issue by dapplion** [eth2-clients/slashing-protection-interchange-tests#5]
Follow eth2-spec-tests to have a downloadable tar in a versioned tagged release

https://github.com/ethereum/eth2.0-spec-tests/releases/tag/v1.0.0

**Comment by michaelsproul** [comment]
Thanks, yeah, this is a good idea. It's on my TODO list when I update EIP-3076 to polish and bundle these tests. Please poke me if I don't get around to it.

**Comment by michaelsproul** [comment]
I made a v5.0.0 with the existing test cases here:

https://github.com/eth2-clients/slashing-protection-interchange-tests/releases/tag/v5.0.0
